/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;


import javax.swing.JOptionPane;

import DAO.ReaderDAO;

/**
 *
 * @author Thang
 * 
 */

//  ForgotPassword f = new ForgotPassword(this);
//  f.setVisible(true);
//  this.setVisible(false);

public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */

    private Login login;
    private Home home;

    public ForgotPassword(Login login, Home home) {
        this.login = login;
        this.home = home;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("Forgot Password");
        getContentPane().setBackground( new java.awt.Color(13,18,130));
        
        lblConfirmationCode.setVisible(false); lblConfirmationCode.setEnabled(false);
        txtConfirmationCode.setVisible(false); txtConfirmationCode.setEnabled(false);
        btnVerifyCode.setVisible(false); btnVerifyCode.setEnabled(false);

        lblChangePassword.setVisible(false); lblChangePassword.setEnabled(false);
        lblNewPassword.setVisible(false); lblNewPassword.setEnabled(false);
        lblRetypeNewPassword.setVisible(false); lblRetypeNewPassword.setEnabled(false);

        txtNewPassword.setVisible(false); txtNewPassword.setEnabled(false);
        txtRetypeNewPassword.setVisible(false); txtRetypeNewPassword.setEnabled(false);
        EyeButton1.setVisible(false); EyeButton1.setEnabled(false);
        EyeButton2.setVisible(false); EyeButton2.setEnabled(false);
        btnEditPassword.setVisible(false); btnEditPassword.setEnabled(false);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                login.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblChangePassword = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        lblRetypeNewPassword = new javax.swing.JLabel();
        txtRetypeNewPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        EyeButton1 = new javax.swing.JButton();
        EyeButton2 = new javax.swing.JButton();
        btnEditPassword = new javax.swing.JButton();
        lblYourEmailAdress = new javax.swing.JLabel();
        btnSendCode = new javax.swing.JButton();
        lblConfirmationCode = new javax.swing.JLabel();
        btnVerifyCode = new javax.swing.JButton();
        txtEmailAdress = new javax.swing.JTextField();
        txtConfirmationCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(13, 18, 130));
        setIconImage(Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/images/1200px-Logo_Hust.png")));

        jPanel1.setBackground(new java.awt.Color(13, 18, 130));

        lblChangePassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblChangePassword.setForeground(new java.awt.Color(255, 255, 0));
        lblChangePassword.setText("Change Password");

        lblNewPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(215, 19, 19));
        lblNewPassword.setText("New Password");

        lblRetypeNewPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRetypeNewPassword.setForeground(new java.awt.Color(215, 19, 19));
        lblRetypeNewPassword.setText("Retype New Password");

        txtRetypeNewPassword.setToolTipText("");

        EyeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        EyeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeButton1ActionPerformed(evt);
            }
        });

        EyeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        EyeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeButton2ActionPerformed(evt);
            }
        });

        btnEditPassword.setBackground(new java.awt.Color(240, 222, 54));
        btnEditPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditPassword.setForeground(new java.awt.Color(215, 19, 19));
        btnEditPassword.setText("Edit Password");
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });

        lblYourEmailAdress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblYourEmailAdress.setForeground(new java.awt.Color(215, 19, 19));
        lblYourEmailAdress.setText("Your Email Adress");

        btnSendCode.setBackground(new java.awt.Color(240, 222, 54));
        btnSendCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSendCode.setForeground(new java.awt.Color(215, 19, 19));
        btnSendCode.setText("Send Code");
        btnSendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCodeActionPerformed(evt);
            }
        });

        lblConfirmationCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblConfirmationCode.setForeground(new java.awt.Color(215, 19, 19));
        lblConfirmationCode.setText("Confirmation code");

        btnVerifyCode.setBackground(new java.awt.Color(240, 222, 54));
        btnVerifyCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerifyCode.setForeground(new java.awt.Color(215, 19, 19));
        btnVerifyCode.setText("Verify Code");
        btnVerifyCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyCodeActionPerformed(evt);
            }
        });

        txtEmailAdress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmailAdress.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        txtConfirmationCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtConfirmationCode.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtConfirmationCode.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChangePassword))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblYourEmailAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtEmailAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRetypeNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRetypeNewPassword)
                                            .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EyeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(EyeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSendCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblConfirmationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConfirmationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblYourEmailAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmailAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSendCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConfirmationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtConfirmationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(lblChangePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRetypeNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtNewPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRetypeNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(EyeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EyeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnEditPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EyeButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (EyeButton1.getIcon().toString().contains("hide")) {
            EyeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtNewPassword.setEchoChar((char) 0);
        } else {
            EyeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtNewPassword.setEchoChar('*');
        }
    }

    private void EyeButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (EyeButton2.getIcon().toString().contains("hide")) {
            EyeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtRetypeNewPassword.setEchoChar((char) 0);
        } else {
            EyeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtRetypeNewPassword.setEchoChar('*');
        }
    }

    private String hashPassword(String password) {
        byte[] temp = password.getBytes();
        byte[] hashData = null;

        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            hashData = md.digest(temp);
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }

        StringBuilder hashPass = new StringBuilder();

        for (byte item : hashData) {
            hashPass.append(Byte.toUnsignedInt(item));
        }

        return hashPass.toString();
    }

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        String newPassword = new String(txtNewPassword.getPassword());
        String retypeNewPassword = new String(txtRetypeNewPassword.getPassword());

        if (newPassword.equals("") || retypeNewPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!newPassword.equals(retypeNewPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (new String(txtNewPassword.getPassword()).matches("^.*\\s.*$")) {
            JOptionPane.showMessageDialog(null, "New password must not have space", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*[A-Z].*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 uppercase character", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*[a-z].*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 lowercase character", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*\\d.*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 digit", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 special character", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (new String(txtNewPassword.getPassword()).length() < 8 || new String(txtNewPassword.getPassword()).length() > 50) {
            JOptionPane.showMessageDialog(null, "New password must have at least 8 characters and at most 50 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 

        String email = txtEmailAdress.getText();
        String idNumber = new ReaderDAO().getIdNumberByEmail(email);

        if (idNumber.equals("NULL")) {
            JOptionPane.showMessageDialog(this, "Email not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            String newPasswordHash = hashPassword(newPassword);
            
            if (new ReaderDAO().editPasswordByIDNumber(idNumber, newPasswordHash)) {
                JOptionPane.showMessageDialog(this, "Password has been changed", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                login.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to change password", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }        
    }

    private String code = "NULL";

    private void btnSendCodeActionPerformed(java.awt.event.ActionEvent evt) {
        String email = txtEmailAdress.getText();

        if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill in Email Adress", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String cardId = new ReaderDAO().getCardIdByEmail(email);

        if (cardId.equals("NULL")) {
            JOptionPane.showMessageDialog(this, "Email not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Code has been sent to your email", "Success", JOptionPane.INFORMATION_MESSAGE);
            code = "123456";

            txtEmailAdress.setEditable(false);

            lblConfirmationCode.setVisible(true); lblConfirmationCode.setEnabled(true);
            txtConfirmationCode.setVisible(true); txtConfirmationCode.setEnabled(true);
            btnVerifyCode.setVisible(true); btnVerifyCode.setEnabled(true);

            return;
        }
    }

    private void btnVerifyCodeActionPerformed(java.awt.event.ActionEvent evt) {
        String codeInput = txtConfirmationCode.getText();

        if (codeInput.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill in Confirmation Code", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (codeInput.equals(code)) {
            JOptionPane.showMessageDialog(this, "Code is correct", "Success", JOptionPane.INFORMATION_MESSAGE);

            lblChangePassword.setVisible(true); lblChangePassword.setEnabled(true);
            lblNewPassword.setVisible(true); lblNewPassword.setEnabled(true);
            lblRetypeNewPassword.setVisible(true); lblRetypeNewPassword.setEnabled(true);

            txtNewPassword.setVisible(true); txtNewPassword.setEnabled(true);
            txtRetypeNewPassword.setVisible(true); txtRetypeNewPassword.setEnabled(true);
            EyeButton1.setVisible(true); EyeButton1.setEnabled(true);
            EyeButton2.setVisible(true); EyeButton2.setEnabled(true);
            btnEditPassword.setVisible(true); btnEditPassword.setEnabled(true);            
        } else {
            JOptionPane.showMessageDialog(this, "Code is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ForgotPassword(new Login(new Home()), new Home()).setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EyeButton1;
    private javax.swing.JButton EyeButton2;
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JButton btnSendCode;
    private javax.swing.JButton btnVerifyCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChangePassword;
    private javax.swing.JLabel lblConfirmationCode;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblRetypeNewPassword;
    private javax.swing.JLabel lblYourEmailAdress;
    private javax.swing.JTextField txtConfirmationCode;
    private javax.swing.JTextField txtEmailAdress;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtRetypeNewPassword;
    // End of variables declaration//GEN-END:variables
}
