/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.WindowAdapter;
import java.sql.Date;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import org.mindrot.jbcrypt.BCrypt;

import DAO.LibrarianDAO;
import model.Librarian;

import java.awt.Toolkit;
import java.awt.Color;


/**
 *
 * @author Thang
 */
public class InfoLibrarian extends javax.swing.JFrame {

    /**
     * Creates new form InfoPerson
     */

    private Home home;

    public InfoLibrarian(Home home, String personIDNumber) {
        this.home = home;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("Library Information");

        setInfo(personIDNumber);

        addWindowListener(new WindowAdapter() {        
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                home.setEnabled(true);
            }
        });
    }

    private void setInfo(String personIDNumber) {
        Librarian librarian = null;
        try {
            librarian = new Librarian();
        } catch (Exception e) {
            e.printStackTrace();
        }

        librarian = new LibrarianDAO().getLibrarianByIDNumber(personIDNumber);

        txtName.setText(librarian.getName());
        txtDOB.setDate(Date.valueOf(librarian.getDob()));
        txtAddress.setText(librarian.getAddress());
        txtGender.setText(librarian.getGender());
        txtPhoneNum.setText(librarian.getPhoneNumber());
        txtEmail.setText(librarian.getEmail());
        txtIDNumber.setText(librarian.getIdNumber());
        txtDepartment.setText(librarian.getDepartment());
        txtPosition.setText(librarian.getPosition());
        txtWorkplace.setText(librarian.getWorkplace());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblWorkplace = new javax.swing.JLabel();
        txtWorkplace = new javax.swing.JTextField();
        btnEditInformation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDOB = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnEditPassword = new javax.swing.JButton();
        EyeButton = new javax.swing.JButton();
        EyeButton1 = new javax.swing.JButton();
        EyeButton2 = new javax.swing.JButton();
        txtOldPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtRetypeNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/images/1200px-Logo_Hust.png")));

        BackgroundPanel.setBackground(new java.awt.Color(13, 18, 130));

        jPanel1.setBackground(new java.awt.Color(13, 18, 130));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(238,237,237)));

        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(215, 19, 19));
        lblName.setText("Name");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtName.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtName.setEnabled(false);

        lblDOB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(215, 19, 19));
        lblDOB.setText("DOB");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(215, 19, 19));
        jLabel23.setText("Address");

        txtAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAddress.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(215, 19, 19));
        jLabel26.setText("Gender");
        jLabel26.setToolTipText("");

        txtGender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGender.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtGender.setEnabled(false);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(215, 19, 19));
        jLabel27.setText("Phone Num");

        txtPhoneNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhoneNum.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(215, 19, 19));
        jLabel28.setText("Email");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(215, 19, 19));
        jLabel29.setText("ID Number");

        txtIDNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIDNumber.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtIDNumber.setEnabled(false);

        lblDepartment.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(215, 19, 19));
        lblDepartment.setText("Deparment");

        txtDepartment.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDepartment.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtDepartment.setEnabled(false);

        lblPosition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(215, 19, 19));
        lblPosition.setText("Position");

        txtPosition.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPosition.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtPosition.setEnabled(false);

        lblWorkplace.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblWorkplace.setForeground(new java.awt.Color(215, 19, 19));
        lblWorkplace.setText("Workplace");

        txtWorkplace.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtWorkplace.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtWorkplace.setEnabled(false);

        btnEditInformation.setBackground(new java.awt.Color(240, 222, 54));
        btnEditInformation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditInformation.setForeground(new java.awt.Color(215, 19, 19));
        btnEditInformation.setText("Edit Information");
        btnEditInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInformationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Personal Information");

        txtDOB.setDateFormatString("yyyy-MM-dd\n");
        txtDOB.setEnabled(false);
        txtDOB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnEditInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(13, 18, 130));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Change Password");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(215, 19, 19));
        jLabel30.setText("Old Password");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(215, 19, 19));
        jLabel31.setText("New Password");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(215, 19, 19));
        jLabel32.setText("Retype New Password");

        btnEditPassword.setBackground(new java.awt.Color(240, 222, 54));
        btnEditPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditPassword.setForeground(new java.awt.Color(215, 19, 19));
        btnEditPassword.setText("Edit Password");
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });

        EyeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        EyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeButtonActionPerformed(evt);
            }
        });

        EyeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        EyeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeButton1ActionPerformed(evt);
            }
        });

        EyeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        EyeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyeButton2ActionPerformed(evt);
            }
        });

        txtRetypeNewPassword.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRetypeNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtNewPassword))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EyeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EyeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EyeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EyeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EyeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EyeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetypeNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EyeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (EyeButton.getIcon().toString().contains("hide")) {
            EyeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtOldPassword.setEchoChar((char) 0);
        } else {
            EyeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtOldPassword.setEchoChar('*');
        }
    }

    private void EyeButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (EyeButton1.getIcon().toString().contains("hide")) {
            EyeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtNewPassword.setEchoChar((char) 0);
        } else {
            EyeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtNewPassword.setEchoChar('*');
        }
    }

    private void EyeButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (EyeButton2.getIcon().toString().contains("hide")) {
            EyeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtRetypeNewPassword.setEchoChar((char) 0);
        } else {
            EyeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtRetypeNewPassword.setEchoChar('*');
        }
    }

    private boolean checkPasswordAcceptable() {
        if (new String(txtOldPassword.getPassword()).equals("") || new String(txtNewPassword.getPassword()).equals("") || new String(txtRetypeNewPassword.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!hashPassword(new String(txtOldPassword.getPassword())).equals(new LibrarianDAO().getPasswordByIDNumber(txtIDNumber.getText()))) {
            JOptionPane.showMessageDialog(null, "Old password is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else

        if (!new String(txtNewPassword.getPassword()).equals(new String(txtRetypeNewPassword.getPassword()))) {
            JOptionPane.showMessageDialog(null, "New password and retype new password must be the same", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } 

        // New password must have at least 8 characters -> at most 50 characters -> no space -> 1 uppercase -> 1 lowercase -> 1 digit -> 1 special character
        if (new String(txtNewPassword.getPassword()).length() < 8 || new String(txtNewPassword.getPassword()).length() > 50) {
            JOptionPane.showMessageDialog(null, "New password must have at least 8 characters and at most 50 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (new String(txtNewPassword.getPassword()).matches("^.*\\s.*$")) {
            JOptionPane.showMessageDialog(null, "New password must not have space", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*[A-Z].*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 uppercase character", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*[a-z].*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 lowercase character", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*\\d.*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 digit", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!new String(txtNewPassword.getPassword()).matches("^.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*$")) {
            JOptionPane.showMessageDialog(null, "New password must have at least 1 special character", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (new String(txtOldPassword.getPassword()).equals(new String(txtNewPassword.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Old password must be different from new password", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private String hashPassword(String password) {
        // Fixed salt
        String fixedSalt = "$2a$10$eImiTXuWVxfM37uY4JANjQ"; 

        // Hash password using BCrypt with fixed salt
        String hashedPassword = BCrypt.hashpw(password, fixedSalt);

        return hashedPassword;
    }

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        if (!checkPasswordAcceptable()) {
            return;
        }

        if (new LibrarianDAO().editPasswordByIDNumber(txtIDNumber.getText(), hashPassword(new String(txtNewPassword.getPassword())))) {
            JOptionPane.showMessageDialog(null, "Change password successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            txtOldPassword.setText("");
            txtNewPassword.setText("");
            txtRetypeNewPassword.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Change password failed", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean checkFieldsAcceptable() {
        if (txtName.getText().equals("") || txtAddress.getText().equals("") || txtGender.getText().equals("") || 
            txtPhoneNum.getText().equals("") || txtEmail.getText().equals("") || txtIDNumber.getText().equals("") || 
            txtDepartment.getText().equals("") || txtPosition.getText().equals("") || txtWorkplace.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // New password must have at least 8 characters -> at most 50 characters -> no space -> 1 uppercase -> 1 lowercase -> 1 digit -> 1 special character -> Old password must be different from new password
        if (!txtPhoneNum.getText().matches("^\\d{10}$")) {
            JOptionPane.showMessageDialog(null, "Phone number must have 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
            JOptionPane.showMessageDialog(null, "Invalid email format", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtIDNumber.getText().matches("^\\d{12}$")) {
            JOptionPane.showMessageDialog(null, "ID number must have 12 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtGender.getText().equals("Male") && !txtGender.getText().equals("Female")) {
            JOptionPane.showMessageDialog(null, "Gender must be Male or Female", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } 

        // Kiểm tra ngày sinh
        String selectDate = ((JTextField) txtDOB.getDateEditor().getUiComponent()).getText();
        if (selectDate.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a DOB", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Kiểm tra xem PhoneNum, email, IDNumber có trùng với người khác không
        if (!txtPhoneNum.getText().equals(new LibrarianDAO().getPhoneNumberByIDNumber(txtIDNumber.getText())) && new LibrarianDAO().checkPhoneNumber(txtPhoneNum.getText())) {
            JOptionPane.showMessageDialog(null, "Another Librarian has this phone number", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtEmail.getText().equals(new LibrarianDAO().getEmailByIDNumber(txtIDNumber.getText())) && new LibrarianDAO().checkEmail(txtEmail.getText())) {
            JOptionPane.showMessageDialog(null, "Another Librarian has this email", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtIDNumber.getText().equals(new LibrarianDAO().getIDNumberByIDNumber(txtIDNumber.getText())) && new LibrarianDAO().checkIDNumber(txtIDNumber.getText())) {
            JOptionPane.showMessageDialog(null, "Another Librarian has this ID number", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private void btnEditInformationActionPerformed(java.awt.event.ActionEvent evt) {
        if (!checkFieldsAcceptable()) {
            setInfo(txtIDNumber.getText());
            return;
        }

        Librarian librarian = null;
        try {
            librarian = new Librarian();
        } catch (Exception e) {
            e.printStackTrace();
        }

        librarian.setName(txtName.getText());
        librarian.setDob(((JTextField) txtDOB.getDateEditor().getUiComponent()).getText());
        librarian.setAddress(txtAddress.getText());
        librarian.setGender(txtGender.getText());
        librarian.setPhoneNumber(txtPhoneNum.getText());
        librarian.setEmail(txtEmail.getText());
        librarian.setIdNumber(txtIDNumber.getText());
        librarian.setDepartment(txtDepartment.getText());
        librarian.setPosition(txtPosition.getText());
        librarian.setWorkplace(txtWorkplace.getText());

        if (new LibrarianDAO().editLibrarian(librarian)) {
            JOptionPane.showMessageDialog(null, "Update information successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Update information failed", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InfoLibrarian(new Home(), null).setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton EyeButton;
    private javax.swing.JButton EyeButton1;
    private javax.swing.JButton EyeButton2;
    private javax.swing.JButton btnEditInformation;
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblWorkplace;
    private javax.swing.JTextField txtAddress;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JPasswordField txtRetypeNewPassword;
    private javax.swing.JTextField txtWorkplace;
    // End of variables declaration//GEN-END:variables
}
